# Generated by Django 5.0.6 on 2024-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_pagamento_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
