# Generated by Django 5.0.6 on 2024-05-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.categoria'),
        ),
    ]
