# Generated by Django 5.0.6 on 2024-05-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_tipo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipos',
            field=models.ManyToManyField(to='loja.tipo'),
        ),
    ]
