# Generated by Django 5.0.6 on 2024-05-27 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_alter_tipo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos', to='loja.categoria'),
        ),
    ]
