# Generated by Django 5.0.6 on 2024-05-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_alter_tipo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='categoria',
        ),
    ]
