# Generated by Django 5.0.6 on 2024-05-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_remove_tipo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='loja.categoria'),
        ),
    ]
