# Generated by Django 5.0.6 on 2024-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0020_tipo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipos',
            field=models.ManyToManyField(related_name='categorias', to='loja.tipo'),
        ),
    ]
