# Generated by Django 5.0.6 on 2024-06-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_apresentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='composicao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
